<html>
<head>
    <title>Cheerios</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <link rel="stylesheet" href="style.css">
</head>
<body>
<div class="cheerio-container"> 
  <center>
		<h1>Cheerios!</h1>

		<form class="pure-form" method="post" action="newCheerio">
			<input name="message" id="message" type="text" size="75" /><br/>
			<input type="submit" class="pure-button" value="Pip Pip" />
		</form>


    <div>
		<?php
			if(!empty($data['cheerios'])) {
				foreach($cheerios as $cheerio) {
					echo '<p class="cheerio-listing">' . $cheerio->getMessage() . '</p>';
				}
			} else {
				echo '<p>No cheerios, post one!</p>';
			}
		?>
    </div>
  </center>
</div>
</body>
